name: Build and Scan
description: Build and Scan

inputs:
  chart_name:
    description: "chart name"
    required: true
  vault_addr:
    description: "vault addr"
    required: true
  vault_namespace:
    description: "vault namespace"
    required: true
  vault_role:
    description: "vault role"
    required: true

runs:
  using: "composite"
  steps:
    - name: Vault Auth
      uses: hashicorp/vault-action@v3.0.0
      id: vault
      with:
        exportEnv: false
        exportToken: true
        url: ${{ inputs.vault_addr }}
        namespace: ${{ inputs.vault_namespace }}
        role: ${{ inputs.vault_role }}
        method: jwt
        secrets: secret/data/svc/snyk snyk_token

    - name: Install Snyk
      uses: snyk/actions/setup@master
      id: snyk

    - name: Snyk version
      shell: bash
      run: echo "${{ steps.snyk.outputs.version }}"

    - name: Helm version
      shell: bash
      run: helm version

    - name: Template and Scan
      shell: bash
      run: |
        helm template --dependency-update --no-hooks ${{ inputs.chart_name }} ./charts/${{ inputs.chart_name }} > tmp-manifest.yaml
        snyk iac test --policy-path=.snyk tmp-manifest.yaml
      env:
        SNYK_TOKEN: ${{ steps.vault.outputs.snyk_token }}
