name: Publish and Sign
description: Publish and Sign

inputs:
  chart_name:
    description: "chart name"
    required: true
  gh_pat:
    description: "gh pat"
    required: true
  vault_addr:
    description: "vault addr"
    required: true
  vault_namespace:
    description: "vault namespace"
    required: true
  vault_role:
    description: "vault role"
    required: true

runs:
  using: "composite"
  steps:
    - name: Vault Auth
      uses: hashicorp/vault-action@v3.0.0
      id: vault
      with:
        exportEnv: false
        exportToken: true
        url: ${{ inputs.vault_addr }}
        namespace: ${{ inputs.vault_namespace }}
        role: ${{ inputs.vault_role }}
        method: jwt
        secrets: secret/data/svc/github image_pull_token | gh_pat

    - name: Package
      shell: bash
      run: |
        helm package ./charts/${{ inputs.chart_name }} --dependency-update --destination ./packages

    - name: Login
      shell: bash
      run: |
        docker login -u username -p ${{ steps.vault.outputs.gh_pat }} ghcr.io/ianhewlett

    - name: Push
      shell: bash
      run: |
        helm push ./packages/${{ inputs.chart_name }}-${{ github.ref_name }}.tgz oci://ghcr.io/ianhewlett/charts

    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.5.0

    - name: Cosign version
      shell: bash
      run: cosign version

    - name: Sign
      shell: bash
      run: |
        cosign sign --key hashivault://image_signing_key \
          ghcr.io/ianhewlett/charts/${{ inputs.chart_name }}:${{ github.ref_name }}
      env:
        VAULT_ADDR: ${{ inputs.vault_addr }}
        VAULT_NAMESPACE: ${{ inputs.vault_namespace }}
